// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: proto/container/container.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"` // Unique identifier for the request
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Vcpu          float64                `protobuf:"fixed64,3,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	Memory        int64                  `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ports         []int32                `protobuf:"varint,6,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunContainerRequest) Reset() {
	*x = RunContainerRequest{}
	mi := &file_proto_container_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunContainerRequest) ProtoMessage() {}

func (x *RunContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunContainerRequest.ProtoReflect.Descriptor instead.
func (*RunContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_container_container_proto_rawDescGZIP(), []int{0}
}

func (x *RunContainerRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RunContainerRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *RunContainerRequest) GetVcpu() float64 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *RunContainerRequest) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *RunContainerRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunContainerRequest) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

type RunContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunContainerResponse) Reset() {
	*x = RunContainerResponse{}
	mi := &file_proto_container_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunContainerResponse) ProtoMessage() {}

func (x *RunContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunContainerResponse.ProtoReflect.Descriptor instead.
func (*RunContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_container_container_proto_rawDescGZIP(), []int{1}
}

func (x *RunContainerResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StopContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainerRequest) Reset() {
	*x = StopContainerRequest{}
	mi := &file_proto_container_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerRequest) ProtoMessage() {}

func (x *StopContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerRequest.ProtoReflect.Descriptor instead.
func (*StopContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_container_container_proto_rawDescGZIP(), []int{2}
}

func (x *StopContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type StopContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainerResponse) Reset() {
	*x = StopContainerResponse{}
	mi := &file_proto_container_container_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerResponse) ProtoMessage() {}

func (x *StopContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_container_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerResponse.ProtoReflect.Descriptor instead.
func (*StopContainerResponse) Descriptor() ([]byte, []int) {
	return file_proto_container_container_proto_rawDescGZIP(), []int{3}
}

type GetContainerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerStatusRequest) Reset() {
	*x = GetContainerStatusRequest{}
	mi := &file_proto_container_container_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerStatusRequest) ProtoMessage() {}

func (x *GetContainerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_container_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetContainerStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_container_container_proto_rawDescGZIP(), []int{4}
}

func (x *GetContainerStatusRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type GetContainerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	VcpuSeconds   float64                `protobuf:"fixed64,2,opt,name=vcpu_seconds,json=vcpuSeconds,proto3" json:"vcpu_seconds,omitempty"`
	RamMbSeconds  float64                `protobuf:"fixed64,3,opt,name=ram_mb_seconds,json=ramMbSeconds,proto3" json:"ram_mb_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerStatusResponse) Reset() {
	*x = GetContainerStatusResponse{}
	mi := &file_proto_container_container_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerStatusResponse) ProtoMessage() {}

func (x *GetContainerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_container_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetContainerStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_container_container_proto_rawDescGZIP(), []int{5}
}

func (x *GetContainerStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetContainerStatusResponse) GetVcpuSeconds() float64 {
	if x != nil {
		return x.VcpuSeconds
	}
	return 0
}

func (x *GetContainerStatusResponse) GetRamMbSeconds() float64 {
	if x != nil {
		return x.RamMbSeconds
	}
	return 0
}

type UsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageRequest) Reset() {
	*x = UsageRequest{}
	mi := &file_proto_container_container_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageRequest) ProtoMessage() {}

func (x *UsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_container_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageRequest.ProtoReflect.Descriptor instead.
func (*UsageRequest) Descriptor() ([]byte, []int) {
	return file_proto_container_container_proto_rawDescGZIP(), []int{6}
}

func (x *UsageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	VcpuSeconds   float64                `protobuf:"fixed64,2,opt,name=vcpu_seconds,json=vcpuSeconds,proto3" json:"vcpu_seconds,omitempty"`
	RamMbSeconds  float64                `protobuf:"fixed64,3,opt,name=ram_mb_seconds,json=ramMbSeconds,proto3" json:"ram_mb_seconds,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageResponse) Reset() {
	*x = UsageResponse{}
	mi := &file_proto_container_container_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageResponse) ProtoMessage() {}

func (x *UsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_container_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageResponse.ProtoReflect.Descriptor instead.
func (*UsageResponse) Descriptor() ([]byte, []int) {
	return file_proto_container_container_proto_rawDescGZIP(), []int{7}
}

func (x *UsageResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *UsageResponse) GetVcpuSeconds() float64 {
	if x != nil {
		return x.VcpuSeconds
	}
	return 0
}

func (x *UsageResponse) GetRamMbSeconds() float64 {
	if x != nil {
		return x.RamMbSeconds
	}
	return 0
}

func (x *UsageResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_container_container_proto protoreflect.FileDescriptor

const file_proto_container_container_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/container/container.proto\x12\tcontainer\"\xfe\x01\n" +
	"\x13RunContainerRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x12\n" +
	"\x04vcpu\x18\x03 \x01(\x01R\x04vcpu\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\x03R\x06memory\x129\n" +
	"\x03env\x18\x05 \x03(\v2'.container.RunContainerRequest.EnvEntryR\x03env\x12\x14\n" +
	"\x05ports\x18\x06 \x03(\x05R\x05ports\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x14RunContainerResponse\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\"8\n" +
	"\x14StopContainerRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\"\x17\n" +
	"\x15StopContainerResponse\"=\n" +
	"\x19GetContainerStatusRequest\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\"}\n" +
	"\x1aGetContainerStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fvcpu_seconds\x18\x02 \x01(\x01R\vvcpuSeconds\x12$\n" +
	"\x0eram_mb_seconds\x18\x03 \x01(\x01R\framMbSeconds\"'\n" +
	"\fUsageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x98\x01\n" +
	"\rUsageResponse\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\tR\vcontainerId\x12!\n" +
	"\fvcpu_seconds\x18\x02 \x01(\x01R\vvcpuSeconds\x12$\n" +
	"\x0eram_mb_seconds\x18\x03 \x01(\x01R\framMbSeconds\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp2\xde\x02\n" +
	"\x10ContainerService\x12O\n" +
	"\fRunContainer\x12\x1e.container.RunContainerRequest\x1a\x1f.container.RunContainerResponse\x12R\n" +
	"\rStopContainer\x12\x1f.container.StopContainerRequest\x1a .container.StopContainerResponse\x12a\n" +
	"\x12GetContainerStatus\x12$.container.GetContainerStatusRequest\x1a%.container.GetContainerStatusResponse\x12B\n" +
	"\vStreamUsage\x12\x17.container.UsageRequest\x1a\x18.container.UsageResponse0\x01B\x14Z\x12proto/container/pbb\x06proto3"

var (
	file_proto_container_container_proto_rawDescOnce sync.Once
	file_proto_container_container_proto_rawDescData []byte
)

func file_proto_container_container_proto_rawDescGZIP() []byte {
	file_proto_container_container_proto_rawDescOnce.Do(func() {
		file_proto_container_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_container_container_proto_rawDesc), len(file_proto_container_container_proto_rawDesc)))
	})
	return file_proto_container_container_proto_rawDescData
}

var file_proto_container_container_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_container_container_proto_goTypes = []any{
	(*RunContainerRequest)(nil),        // 0: container.RunContainerRequest
	(*RunContainerResponse)(nil),       // 1: container.RunContainerResponse
	(*StopContainerRequest)(nil),       // 2: container.StopContainerRequest
	(*StopContainerResponse)(nil),      // 3: container.StopContainerResponse
	(*GetContainerStatusRequest)(nil),  // 4: container.GetContainerStatusRequest
	(*GetContainerStatusResponse)(nil), // 5: container.GetContainerStatusResponse
	(*UsageRequest)(nil),               // 6: container.UsageRequest
	(*UsageResponse)(nil),              // 7: container.UsageResponse
	nil,                                // 8: container.RunContainerRequest.EnvEntry
}
var file_proto_container_container_proto_depIdxs = []int32{
	8, // 0: container.RunContainerRequest.env:type_name -> container.RunContainerRequest.EnvEntry
	0, // 1: container.ContainerService.RunContainer:input_type -> container.RunContainerRequest
	2, // 2: container.ContainerService.StopContainer:input_type -> container.StopContainerRequest
	4, // 3: container.ContainerService.GetContainerStatus:input_type -> container.GetContainerStatusRequest
	6, // 4: container.ContainerService.StreamUsage:input_type -> container.UsageRequest
	1, // 5: container.ContainerService.RunContainer:output_type -> container.RunContainerResponse
	3, // 6: container.ContainerService.StopContainer:output_type -> container.StopContainerResponse
	5, // 7: container.ContainerService.GetContainerStatus:output_type -> container.GetContainerStatusResponse
	7, // 8: container.ContainerService.StreamUsage:output_type -> container.UsageResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_container_container_proto_init() }
func file_proto_container_container_proto_init() {
	if File_proto_container_container_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_container_container_proto_rawDesc), len(file_proto_container_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_container_container_proto_goTypes,
		DependencyIndexes: file_proto_container_container_proto_depIdxs,
		MessageInfos:      file_proto_container_container_proto_msgTypes,
	}.Build()
	File_proto_container_container_proto = out.File
	file_proto_container_container_proto_goTypes = nil
	file_proto_container_container_proto_depIdxs = nil
}
